language: rust

rust:
  - stable

script: cargo build --release;

matrix:
  fast_finish: true

os:
  - linux
  - osx
  - windows

before_deploy:
  - "if [[ -f target/release/pegtx ]]; then mv target/release/pegtx \"target/release/pegtx-$TRAVIS_TAG-$TRAVIS_OS_NAME\"; fi"
  - "if [[ -f target/release/pegtx.exe ]]; then mv target/release/pegtx.exe \"target/release/pegtx-$TRAVIS_TAG-$TRAVIS_OS_NAME.exe\"; fi"
  - ls target/release/

deploy:
  - provider: cargo
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable && $TRAVIS_OS_NAME = linux"
      branch: master
    token:
      secure: $CARGODEPLOY
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file_glob: true
    file:
      - target/release/pegtx-*
    api_key:
      secure: $GHDEPLOY